export const LoginAuth = {
  LOGIN_REQUEST: 'LOGIN_USER_REQUEST',
  LOGIN_REQUEST_SUCCESSFUL: 'LOGIN_USER_REQUEST_SUCCESSFUL',
  LOGIN_REQUEST_FAILED: 'LOGIN_USER_REQUEST_FAILED',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_REQUEST_SUCCESS: 'LOGOUT_REQUEST_SUCCESS',
  LOGOUT_REQUEST_FAILED: 'LOGOUT_REQUEST_FAILED',
};

//

export const Summit = {
  SUMMIT_FETCH: 'SUMMIT_FETCH',
  SUMMIT_SUCCESS: 'SUMMIT_SUCCESS',
  SUMMIT_FAILED: 'SUMMIT_FAILED',
};

// export const Project = {
//   PROJECT_FETCH: 'PROJECT_FETCH',
//   PROJECT_SUCCESS: 'PROJECT_SUCCESS',
//   PROJECT_FAILED: 'PROJECT_FAILED',
// };

export const Event = {
  EVENT_FETCH: 'EVENT_FETCH',
  EVENT_SUCCESS: 'EVENT_SUCCESS',
  EVENT_FAILED: 'EVENT_FAILED',
};
export const Blog = {
  BLOG_FETCH: 'BLOG_FETCH',
  BLOG_SUCCESS: 'BLOG_SUCCESS',
  BLOG_FAILED: 'BLOG_FAILED',
};

export const PartnerForm = {
  PARTNERFORM_FETCH: 'PARTNERFORM_FETCH',
  PARTNERFORM_SUCCESS: 'PARTNERFORM_SUCCESS',
  PARTNERFORM_FAILED: 'PARTNERFORM_FAILED',
};

export const Project = {
  PROJECT_FETCH: 'PROJECT_FETCH',
  PROJECT_SUCCESS: 'PROJECT_SUCCESS',
  PROJECT_FAILED: 'PROJECT_FAILED',
};

// export const getPartner = {
//   GET_PARTNER_FETCH: 'GET_PARTNER_FETCH',
//   GET_PARTNER_SUCCESS: 'GET_PARTNER_SUCCESS',
//   GET_PARTNER_FAILED: 'GET_PARTNER_FAILED',
// };

// export const Media = {
//   MEDIA_FETCH: 'MEDIA_FETCH',
//   MEDIA_SUCCESS: 'MEDIA_SUCCESS',
//   MEDIA_FAILED: 'MEDIA_FAILED',
// };

// export const Video = {
//   VIDEO_FETCH: 'VIDEO_FETCH',
//   VIDEO_SUCCESS: 'VIDEO_SUCCESS',
//   VIDEO_FAILED: 'VIDEO_FAILED',
// };

// export const Video = {
//   VIDEO_FETCH: 'VIDEO_FETCH',
//   VIDEO_SUCCESS: 'VIDEO_SUCCESS',
//   VIDEO_FAILED: 'VIDEO_FAILED',
// };

export const Team = {
  TEAM_FETCH: 'TEAM_FETCH',
  TEAM_SUCCESS: 'TEAM_SUCCESS',
  TEAM_FAILED: 'TEAM_FAILED',
};

export const Volunteers = {
  VOLUNTEERS_REQUEST: 'VOLUNTEERS_REQUEST',
  VOLUNTEERS_SUCCESS: 'VOLUNTEERS_SUCCESS',
  VOLUNTEERS_FAILED: 'VOLUNTEERS_FAILED',
};

export const Consultations = {
  CONSULTATIONS_REQUEST: ' CONSULTATIONS_REQUEST',
  CONSULTATIONS_SUCCESS: ' CONSULTATIONS_SUCCESS',
  CONSULTATIONS_FAILED: ' CONSULTATIONS_FAILED',
};
